In [518]:
#Libraries import for this Analysis

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error

#Any other library will be add as at when neccessary 


In [519]:
#loading the data into a Pandas DataFrame

df = pd.read_csv("C:/Users/stanley/Downloads/Honda Dataset.csv", encoding='ISO-8859-1')


In [520]:
df

Year   Make                      Model Condition     Price  \
0     2023  Honda              Ridgeline RTL       New  $46,370    
1     2023  Honda          CR-V Hybrid Sport       New  $34,150    
2     2023  Honda          CR-V Hybrid Sport       New  $34,245    
3     2022  Honda           Pilot TrailSport       New  $46,500    
4     2023  Honda  CR-V Hybrid Sport Touring       New  $40,395    
...    ...    ...                        ...       ...       ...   
4994  2018  Honda               Accord Sport      Used  $19,999    
4995  2020  Honda                     Fit LX      Used  $17,495    
4996  2018  Honda                Civic Sport      Used  $19,500    
4997  2011  Honda                Accord EX-L      Used  $17,998    
4998  2023  Honda                Pilot Elite       New  $53,325    

      Consumer_Rating  Consumer_Review_#           Exterior_Color  \
0                 4.8                  9     Platinum White Pearl   
1                 1.7                 24     Platinum White Pearl   
2                 4.7               2869  Meteorite Gray Metallic   
3                 5.0                 12         Sonic Gray Pearl   
4                 4.4                 12      Crystal Black Pearl   
...               ...                ...                      ...   
4994              5.0               3234                    White   
4995              4.3                 54                      Red   
4996              4.3               1925       White Orchid Pearl   
4997              4.6                  4                    Black   
4998              4.3                240    Modern Steel Metallic   

     Interior_Color         Drivetrain  ...    Stock_# Mileage Comfort_Rating  \
0             Beige    All-wheel Drive  ...     830164      10            5.0   
1             Black                FWD  ...    6402953       –            5.0   
2             Black  Front-wheel Drive  ...   PH704805       1            5.0   
3             Black    All-wheel Drive  ...   5700429B       5            5.0   
4             Black    All-wheel Drive  ...    5705954       5            5.0   
...             ...                ...  ...        ...     ...            ...   
4994          Black  Front-wheel Drive  ...     U20361   64719            4.8   
4995          Black  Front-wheel Drive  ...      36117   40902            4.7   
4996          Beige  Front-wheel Drive  ...  NA073727A   82906            4.7   
4997          Black  Front-wheel Drive  ...   22941503   88050            4.4   
4998          Brown    All-wheel Drive  ...    H000466       0            NaN   

     Interior_Design_Rating Performance_Rating Value_For_Money_Rating  \
0                       4.8                4.8                    4.2   
1                       3.0                4.0                    4.0   
2                       3.0                4.0                    4.0   
3                       5.0                5.0                    5.0   
4                       3.0                4.0                    4.0   
...                     ...                ...                    ...   
4994                    4.8                4.7                    4.7   
4995                    4.6                4.7                    4.8   
4996                    4.7                4.8                    4.8   
4997                    4.5                4.4                    4.6   
4998                    NaN                NaN                    NaN   

     Exterior_Styling_Rating  Reliability_Rating  State  Seller_Type  
0                        5.0                 5.0     CA       Dealer  
1                        5.0                 5.0     CA       Dealer  
2                        5.0                 5.0     CA       Dealer  
3                        5.0                 5.0     CA       Dealer  
4                        5.0                 5.0     CA       Dealer  
...                      ...                 ...    ...          ...  
4994         


<font size="5">STRUCTRURE OF THE DATA</font>

In [521]:
df.describe().T

count         mean          std     min     25%  \
Year                     4999.0  2020.507702     3.711361  1981.0  2019.0   
Consumer_Rating          4999.0     4.569654     0.542453     1.2     4.4   
Consumer_Review_#        4999.0  1288.366673  1969.998095     0.0   126.0   
Comfort_Rating           4447.0     4.817540     0.259030     3.8     4.7   
Interior_Design_Rating   4447.0     4.706814     0.476941     3.0     4.7   
Performance_Rating       4447.0     4.663931     0.351680     3.6     4.5   
Value_For_Money_Rating   4447.0     4.580976     0.372107     3.6     4.2   
Exterior_Styling_Rating  4447.0     4.731954     0.313093     3.9     4.6   
Reliability_Rating       4447.0     4.866269     0.190886     4.0     4.8   

                            50%     75%      max  
Year                     2022.0  2023.0   2023.0  
Consumer_Rating             4.7     4.9      5.0  
Consumer_Review_#         697.0  1695.5  29258.0  
Comfort_Rating              4.9     5.0      5.0  
Interior_Design_Rating      4.8     5.0      5.0  
Performance_Rating          4.8     5.0      5.0  
Value_For_Money_Rating      4.6     5.0      5.0  
Exterior_Styling_Rating     4.8     5.0      5.0  
Reliability_Rating          5.0     5.0      5.0

In [522]:
#Number of Rows and Columns
num_rows = df.shape[0]
num_cols = df.shape[1]

print("Number of rows:", num_rows)
print("Number of columns:", num_cols)

Number of rows: 4999
Number of columns: 25


In [523]:
df.head()

Year   Make                      Model Condition     Price  \
0  2023  Honda              Ridgeline RTL       New  $46,370    
1  2023  Honda          CR-V Hybrid Sport       New  $34,150    
2  2023  Honda          CR-V Hybrid Sport       New  $34,245    
3  2022  Honda           Pilot TrailSport       New  $46,500    
4  2023  Honda  CR-V Hybrid Sport Touring       New  $40,395    

   Consumer_Rating  Consumer_Review_#           Exterior_Color Interior_Color  \
0              4.8                  9     Platinum White Pearl          Beige   
1              1.7                 24     Platinum White Pearl          Black   
2              4.7               2869  Meteorite Gray Metallic          Black   
3              5.0                 12         Sonic Gray Pearl          Black   
4              4.4                 12      Crystal Black Pearl          Black   

          Drivetrain  ...   Stock_# Mileage Comfort_Rating  \
0    All-wheel Drive  ...    830164      10            5.0   
1                FWD  ...   6402953       –            5.0   
2  Front-wheel Drive  ...  PH704805       1            5.0   
3    All-wheel Drive  ...  5700429B       5            5.0   
4    All-wheel Drive  ...   5705954       5            5.0   

  Interior_Design_Rating Performance_Rating Value_For_Money_Rating  \
0                    4.8                4.8                    4.2   
1                    3.0                4.0                    4.0   
2                    3.0                4.0                    4.0   
3                    5.0                5.0                    5.0   
4                    3.0                4.0                    4.0   

  Exterior_Styling_Rating  Reliability_Rating  State  Seller_Type  
0                     5.0                 5.0     CA       Dealer  
1                     5.0                 5.0     CA       Dealer  
2                     5.0                 5.0     CA       Dealer  
3                     5.0                 5.0     CA       Dealer  
4                     5.0                 5.0     CA       Dealer  

[5 rows x 25 columns]

In [524]:
df.tail()

Year   Make         Model Condition     Price  Consumer_Rating  \
4994  2018  Honda  Accord Sport      Used  $19,999               5.0   
4995  2020  Honda        Fit LX      Used  $17,495               4.3   
4996  2018  Honda   Civic Sport      Used  $19,500               4.3   
4997  2011  Honda   Accord EX-L      Used  $17,998               4.6   
4998  2023  Honda   Pilot Elite       New  $53,325               4.3   

      Consumer_Review_#         Exterior_Color Interior_Color  \
4994               3234                  White          Black   
4995                 54                    Red          Black   
4996               1925     White Orchid Pearl          Beige   
4997                  4                  Black          Black   
4998                240  Modern Steel Metallic          Brown   

             Drivetrain  ...    Stock_# Mileage Comfort_Rating  \
4994  Front-wheel Drive  ...     U20361   64719            4.8   
4995  Front-wheel Drive  ...      36117   40902            4.7   
4996  Front-wheel Drive  ...  NA073727A   82906            4.7   
4997  Front-wheel Drive  ...   22941503   88050            4.4   
4998    All-wheel Drive  ...    H000466       0            NaN   

     Interior_Design_Rating Performance_Rating Value_For_Money_Rating  \
4994                    4.8                4.7                    4.7   
4995                    4.6                4.7                    4.8   
4996                    4.7                4.8                    4.8   
4997                    4.5                4.4                    4.6   
4998                    NaN                NaN                    NaN   

     Exterior_Styling_Rating  Reliability_Rating  State  Seller_Type  
4994                     4.8                 4.8     NY       Dealer  
4995                     4.5                 4.8     NY       Dealer  
4996                     4.9                 4.8     CT       Dealer  
4997                     4.5                 4.8     MA       Dealer  
4998                     NaN                 NaN     ME       Dealer  

[5 rows x 25 columns]

In [525]:
df.columns

Index(['Year', 'Make', 'Model', 'Condition', 'Price', 'Consumer_Rating',
       'Consumer_Review_#', 'Exterior_Color', 'Interior_Color', 'Drivetrain',
       'MPG', 'Fuel_Type', 'Transmission', 'Engine', 'VIN', 'Stock_#',
       'Mileage', 'Comfort_Rating', 'Interior_Design_Rating',
       'Performance_Rating', 'Value_For_Money_Rating',
       'Exterior_Styling_Rating', 'Reliability_Rating', 'State',
       'Seller_Type'],
      dtype='object')

In [526]:
#Checking the data types of each Column
df.dtypes

Year                         int64
Make                        object
Model                       object
Condition                   object
Price                       object
Consumer_Rating            float64
Consumer_Review_#            int64
Exterior_Color              object
Interior_Color              object
Drivetrain                  object
MPG                         object
Fuel_Type                   object
Transmission                object
Engine                      object
VIN                         object
Stock_#                     object
Mileage                     object
Comfort_Rating             float64
Interior_Design_Rating     float64
Performance_Rating         float64
Value_For_Money_Rating     float64
Exterior_Styling_Rating    float64
Reliability_Rating         float64
State                       object
Seller_Type                 object
dtype: object

<font size="5"> CHECKING FOR MISSION VALUES</font>

In [527]:
#checking for missing values
df.isna().any()


Year                       False
Make                       False
Model                      False
Condition                  False
Price                      False
Consumer_Rating            False
Consumer_Review_#          False
Exterior_Color              True
Interior_Color              True
Drivetrain                  True
MPG                         True
Fuel_Type                   True
Transmission                True
Engine                      True
VIN                         True
Stock_#                     True
Mileage                     True
Comfort_Rating              True
Interior_Design_Rating      True
Performance_Rating          True
Value_For_Money_Rating      True
Exterior_Styling_Rating     True
Reliability_Rating          True
State                       True
Seller_Type                 True
dtype: bool

In [528]:
#summing up missing values in each column
df.isna().sum()

Year                          0
Make                          0
Model                         0
Condition                     0
Price                         0
Consumer_Rating               0
Consumer_Review_#             0
Exterior_Color               11
Interior_Color               11
Drivetrain                   11
MPG                        1485
Fuel_Type                    11
Transmission                 11
Engine                       11
VIN                          11
Stock_#                      11
Mileage                      11
Comfort_Rating              552
Interior_Design_Rating      552
Performance_Rating          552
Value_For_Money_Rating      552
Exterior_Styling_Rating     552
Reliability_Rating          552
State                        73
Seller_Type                  73
dtype: int64


<font size="5"> Droping Some NA Values</font>

In [529]:
'''Dropping NA in Exterior and interior_color column
since they are only 11 and won't a major impact 
on the analysis of this dataset'''

df.dropna(subset=["Exterior_Color", "Interior_Color", "Fuel_Type", "Transmission", "Engine"], inplace=True)

In [530]:
df.Exterior_Color.unique()

array(['Platinum White Pearl', 'Meteorite Gray Metallic',
       'Sonic Gray Pearl', 'Crystal Black Pearl',
       'Pacific Pewter Metallic', 'Urban Gray Pearl', 'Still Night Pearl',
       'Modern Steel Metallic', 'Dark Cherry Pearl',
       'Lunar Silver Metallic', 'White', 'Sky', 'Obsidian Blue Pearl',
       'Rallye Red', 'Radiant Red Metallic II', '\x96', 'Silver', 'Black',
       'CRYSTAL BLACK', 'Platinum', 'Gray', 'Platinum White',
       'Silver Metallic', 'Obsidian Black', 'Pewter', 'Midnight Amethyst',
       'Radiant Red', 'Canyon', 'White Pearl', 'Lunar', 'Crystal',
       'Aegean Blue Metallic', 'GC', 'Urban Gray', 'Pearl',
       'Deep Scarlet Pearl', 'Radiant Red Metallic', 'Meteorite', 'Blue',
       'Gold', 'Sonic Blue', 'Still Night', 'Crystal Black',
       'Lunar Silver', 'Milano Red', 'Steel Sapphire Metallic',
       'Obsidian Blue', 'Morning Mist Metallic',
       'Polished Metal Metallic', 'Purple', 'Red', 'Brown',
       'San Marino Red', 'White Diamond Pearl'

In [531]:

# create a list of values to drop
values_to_drop = ['\x96', '1', 'UNKNOWN', 'NH-731P/CRYSTAL BL', 'WX / WX']

# drop the values from the column 'Exterior_Color'
df = df[~df['Exterior_Color'].isin(values_to_drop)]

In [532]:
df.Exterior_Color.unique()

array(['Platinum White Pearl', 'Meteorite Gray Metallic',
       'Sonic Gray Pearl', 'Crystal Black Pearl',
       'Pacific Pewter Metallic', 'Urban Gray Pearl', 'Still Night Pearl',
       'Modern Steel Metallic', 'Dark Cherry Pearl',
       'Lunar Silver Metallic', 'White', 'Sky', 'Obsidian Blue Pearl',
       'Rallye Red', 'Radiant Red Metallic II', 'Silver', 'Black',
       'CRYSTAL BLACK', 'Platinum', 'Gray', 'Platinum White',
       'Silver Metallic', 'Obsidian Black', 'Pewter', 'Midnight Amethyst',
       'Radiant Red', 'Canyon', 'White Pearl', 'Lunar', 'Crystal',
       'Aegean Blue Metallic', 'GC', 'Urban Gray', 'Pearl',
       'Deep Scarlet Pearl', 'Radiant Red Metallic', 'Meteorite', 'Blue',
       'Gold', 'Sonic Blue', 'Still Night', 'Crystal Black',
       'Lunar Silver', 'Milano Red', 'Steel Sapphire Metallic',
       'Obsidian Blue', 'Morning Mist Metallic',
       'Polished Metal Metallic', 'Purple', 'Red', 'Brown',
       'San Marino Red', 'White Diamond Pearl', 'Meteo

In [533]:
df.Interior_Color.unique()

array(['Beige', 'Black', 'Mocha', '\x96', 'Brown', 'Gray',
       'Nh-883p/Black', 'Blk Lth', 'Blk Lth-Trmmed Seats', 'Ivory',
       'Black / Red', 'Red / Black', 'NH-797M/BLACK', 'Gry Clth',
       'NH-912P/BLACK', 'NH-877P/BLACK', 'Blk Perforated Lth-Trmmed',
       'Tan', 'Black/Red', 'Red', 'YR-642M/BLACK', 'NH-883P/BLACK',
       'NH-904M/BLACK', 'NH-731P/BLACK', 'Titanium', 'Truffle',
       'Blk Fabric W/Synthetic Lt', 'Sport', 'Blk Perforated Lth',
       'Black / Gray', 'Nh-797m/Black', 'B-593M/BLACK', 'Gray / Silver',
       'Blk Clth', 'Gry Lth', 'Biege', 'Cream', 'Bge Lth', 'Parchment',
       'Grey', 'Blue', 'Crystal Black', 'B-640m/Black', '.', 'Stone',
       'Graphite', 'Black / Titanium', 'Gray / Blue', 'Blk Lth-Trmmed',
       'Select', 'B-637p/Black', 'Gray/Blue', 'NH-830M/BLACK',
       'Black / Ivory', 'BLACK', 'Interior', 'Burgundy', 'Gray/Black',
       'Silver', 'B-575p/Black', 'Nh-877p/Black',
       'Nighthawk Black Pearl / Grey'], dtype=object)

In [534]:
df.Fuel_Type.unique()

array(['Gasoline', 'Hybrid', '5-Speed A/T', 'A/T', '6-Speed M/T',
       'CVT Transmission', 'Compressed Natural Gas'], dtype=object)

In [535]:
# create a list of values to drop
Non_Fuel_values = ['5-Speed A/T', 'A/T', '6-Speed M/T','CVT Transmission']

# drop the values from the column 'Exterior_Color'
df = df[~df['Fuel_Type'].isin(Non_Fuel_values)]

In [536]:
df.Fuel_Type.unique()

array(['Gasoline', 'Hybrid', 'Compressed Natural Gas'], dtype=object)

In [537]:
df.Transmission.unique()

array(['Automatic', 'Automatic CVT', '9-Speed Automatic',
       '10-Speed Automatic', '10-SPEED A/T', 'continuously variable',
       'continuously variable (m cvt)', 'continuously variable automatic',
       'electronic continuously variable', '1-Speed CVT with Overdrive',
       '9-SPEED A/T', 'Variable', '\x96', 'OTHER', '6-Speed Manual',
       '9-Speed Automatic with Overdrive', 'eCVT', 'Manual',
       'continuously variable w/sport mode',
       'continuously variable (ll cvt)', '10 speed automatic',
       '1-Speed Automatic', 'NOT SPECIFIED', 'CVT',
       'Electronically Controlled Automatic', '6-SPEED M/T',
       '5-Speed Automatic', '6-Speed Automatic',
       '10-Speed Automatic with Overdrive', '4-Speed Automatic', '2',
       '9 speed automatic', '5-Speed Manual', '6-SPEED A/T',
       '5-SPEED A/T', 'TRANSMISSION W DRIVER SELECTABLE MODE',
       'Close-Ratio 6-Speed Manual', '5-SPEED M/T', '4-SPEED A/T',
       'continuously variable (cvt)', 'AUTOMATIC',
       'e co

In [538]:
# create a list of values to drop
Non_Transmission_values = ["\x96","NOT SPECIFIED","2"]

# drop the values from the column 'Exterior_Color'
df = df[~df['Transmission'].isin(Non_Transmission_values)]

In [539]:
df.Interior_Color.unique()

array(['Beige', 'Black', 'Mocha', '\x96', 'Brown', 'Gray',
       'Nh-883p/Black', 'Blk Lth', 'Blk Lth-Trmmed Seats', 'Ivory',
       'Black / Red', 'Red / Black', 'NH-797M/BLACK', 'Gry Clth',
       'NH-912P/BLACK', 'NH-877P/BLACK', 'Blk Perforated Lth-Trmmed',
       'Tan', 'Black/Red', 'Red', 'YR-642M/BLACK', 'NH-883P/BLACK',
       'NH-904M/BLACK', 'NH-731P/BLACK', 'Titanium', 'Truffle',
       'Blk Fabric W/Synthetic Lt', 'Sport', 'Blk Perforated Lth',
       'Black / Gray', 'Nh-797m/Black', 'B-593M/BLACK', 'Gray / Silver',
       'Blk Clth', 'Gry Lth', 'Biege', 'Cream', 'Bge Lth', 'Parchment',
       'Grey', 'Blue', 'Crystal Black', 'B-640m/Black', '.', 'Stone',
       'Graphite', 'Black / Titanium', 'Gray / Blue', 'Blk Lth-Trmmed',
       'Select', 'B-637p/Black', 'Gray/Blue', 'NH-830M/BLACK',
       'Black / Ivory', 'BLACK', 'Interior', 'Burgundy', 'Gray/Black',
       'Silver', 'B-575p/Black', 'Nh-877p/Black',
       'Nighthawk Black Pearl / Grey'], dtype=object)

In [540]:
df.Transmission.unique()

array(['Automatic', 'Automatic CVT', '9-Speed Automatic',
       '10-Speed Automatic', '10-SPEED A/T', 'continuously variable',
       'continuously variable (m cvt)', 'continuously variable automatic',
       'electronic continuously variable', '1-Speed CVT with Overdrive',
       '9-SPEED A/T', 'Variable', 'OTHER', '6-Speed Manual',
       '9-Speed Automatic with Overdrive', 'eCVT', 'Manual',
       'continuously variable w/sport mode',
       'continuously variable (ll cvt)', '10 speed automatic',
       '1-Speed Automatic', 'CVT', 'Electronically Controlled Automatic',
       '6-SPEED M/T', '5-Speed Automatic', '6-Speed Automatic',
       '10-Speed Automatic with Overdrive', '4-Speed Automatic',
       '9 speed automatic', '5-Speed Manual', '6-SPEED A/T',
       '5-SPEED A/T', 'TRANSMISSION W DRIVER SELECTABLE MODE',
       'Close-Ratio 6-Speed Manual', '5-SPEED M/T', '4-SPEED A/T',
       'continuously variable (cvt)', 'AUTOMATIC',
       'e continuously variable (e cvt)',
       

In [541]:
df.Engine.unique()

array(['3.5L V6 24V GDI SOHC', '2.0L I4 16V GDI DOHC Hybrid',
       '3.5L V6 24V GDI DOHC', '1.5L I4 16V GDI DOHC Turbo',
       'V6 Cylinder Engine', '4 Cylinder Engine', '1.5L I4 16V DOHC',
       '2.0L I4 16V GDI DOHC Turbo', '2.0L I4 16V MPFI DOHC Hybrid',
       'Intercooled Turbo Regular Unleaded I-4 1.5 L/91',
       '2.0L I4 16V GDI DOHC', '1.8L I4 16V MPFI SOHC',
       'Gas/Electric I-4 2.0 L/122',
       'Intercooled Turbo Regular Unleaded I-4 2.0 L/122',
       'Regular Unleaded V-6 3.5 L/212', '1.5L 4 Cylinder',
       '2.4L I4 16V GDI DOHC', 'Regular Unleaded I-4 2.0 L/122',
       'Premium Unleaded V-6 3.5 L/212', '2.4L I4 16V MPFI DOHC',
       '1.5L I4 16V MPFI DOHC Hybrid', '2.0L I4 16V MPFI DOHC',
       '2.2L I4 16V MPFI DOHC', '3.5L V6 24V MPFI SOHC', '1.5L 4 Cyl.',
       'Gas/Electric I-4 1.5 L/91', '3.0L V6 24V MPFI SOHC',
       '2.2L I4 16V MPFI SOHC', '1.5L I4', '3.5L', '3.5L V6 DOHC 24V',
       '1.5L I4 16V MPFI SOHC Hybrid', 'Gas/Electric I4 1.5L/91',
   

In [542]:
df.isna().sum()

Year                          0
Make                          0
Model                         0
Condition                     0
Price                         0
Consumer_Rating               0
Consumer_Review_#             0
Exterior_Color                0
Interior_Color                0
Drivetrain                    0
MPG                        1419
Fuel_Type                     0
Transmission                  0
Engine                        0
VIN                           0
Stock_#                       0
Mileage                       0
Comfort_Rating              528
Interior_Design_Rating      528
Performance_Rating          528
Value_For_Money_Rating      528
Exterior_Styling_Rating     528
Reliability_Rating          528
State                        62
Seller_Type                  62
dtype: int64

In [543]:
'''filling the missing values in Comfort and Performance_Rating cloumns
with their means'''


df["Comfort_Rating"].fillna(value=df["Comfort_Rating"].mean(), inplace=True)
df["Performance_Rating"].fillna(value=df["Performance_Rating"].mean(), inplace=True)

In [544]:
df.isna().sum()

Year                          0
Make                          0
Model                         0
Condition                     0
Price                         0
Consumer_Rating               0
Consumer_Review_#             0
Exterior_Color                0
Interior_Color                0
Drivetrain                    0
MPG                        1419
Fuel_Type                     0
Transmission                  0
Engine                        0
VIN                           0
Stock_#                       0
Mileage                       0
Comfort_Rating                0
Interior_Design_Rating      528
Performance_Rating            0
Value_For_Money_Rating      528
Exterior_Styling_Rating     528
Reliability_Rating          528
State                        62
Seller_Type                  62
dtype: int64

<font size="5">Price</font>

In [545]:
# replace 'Not Priced' with NaN
df['Price'] = df['Price'].replace('Not Priced', np.nan)

# drop NaN values since the empty values are few 
df.dropna(subset=['Price'], inplace=True)

# convert Price to a float
df['Price'] = df['Price'].replace('[\$,]', '', regex=True).astype(float)

In [546]:
#Now Price is a Float
df.dtypes

Year                         int64
Make                        object
Model                       object
Condition                   object
Price                      float64
Consumer_Rating            float64
Consumer_Review_#            int64
Exterior_Color              object
Interior_Color              object
Drivetrain                  object
MPG                         object
Fuel_Type                   object
Transmission                object
Engine                      object
VIN                         object
Stock_#                     object
Mileage                     object
Comfort_Rating             float64
Interior_Design_Rating     float64
Performance_Rating         float64
Value_For_Money_Rating     float64
Exterior_Styling_Rating    float64
Reliability_Rating         float64
State                       object
Seller_Type                 object
dtype: object

<font size="5"> Recoding Columns for the Analysis</font>

In [547]:
df.Year.unique()


array([2023, 2022, 2017, 2016, 2021, 2020, 2014, 2019, 2018, 2011, 2000,
       2009, 2004, 2015, 2007, 1997, 2012, 2013, 2010, 2008, 2005, 1981,
       2006, 2002, 1989, 1987, 2003, 1991, 1992, 2001, 1998, 1999, 1993],
      dtype=int64)

In [548]:
#Recoding the enteries in this column to numeric

Years = {}
code = 1
for Year in df.Year.unique():
    Years[Year] = code
    code+=1
    
df.replace(Years, inplace=True) 

In [549]:
df.Year.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
      dtype=int64)

In [550]:
df.Make.unique()

array(['Honda'], dtype=object)

In [551]:
#Recoding the enteries in this column to numeric

Cars = {}
code = 1
for car in df.Make.unique():
    Cars[car] = code
    code+=1
    
df.replace(Cars, inplace=True) 

In [552]:
df.Make.unique()

array([1], dtype=int64)

In [553]:
df.Model.unique()

array(['Ridgeline RTL', 'CR-V Hybrid Sport', 'Pilot TrailSport',
       'CR-V Hybrid Sport Touring', 'Odyssey EX-L', 'Pilot Elite',
       'Pilot Special Edition', 'CR-V EX-L', 'Pilot Sport',
       'Ridgeline RTL-E', 'Passport Elite', 'Accord Sport 1.5T',
       'HR-V Sport', 'Civic Sport', 'Accord Sport 2.0T', 'Accord EX',
       'Pilot EX-L', 'CR-V EX', 'Odyssey Sport', 'Passport EX-L',
       'Passport TrailSport', 'CR-V Touring', 'Pilot Touring 8-Passenger',
       'Accord Hybrid Sport', 'Ridgeline Black Edition',
       'Accord Sport SE', 'Odyssey Elite', 'Pilot Touring 7-Passenger',
       'HR-V LX', 'HR-V EX-L', 'Odyssey Touring', 'Civic Touring',
       'Pilot Black Edition', 'Accord Touring', 'Civic Si Base',
       'Accord Hybrid Sport-L', 'Pilot EX-L 7-Passenger',
       'Accord Hybrid Touring', 'Pilot EX-L 8-Passenger',
       'Accord Hybrid Base', 'Accord EX-L 1.5T', 'Civic EX-L',
       'Pilot Touring', 'Civic EX', 'HR-V EX', 'Civic Sport Touring',
       'Accord Sport',

In [554]:
#Recoding the enteries in this column to numeric

Models = {}
code = 1
for model in df.Model.unique():
    Models[model] = code
    code+=1
    
df.replace(Models, inplace=True) 

In [555]:
df.Model.unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146], dtype=int64)

In [556]:
df.Condition.unique()

array(['New', 'Used', 'Honda Certified'], dtype=object)

In [557]:
#Recoding the enteries in this column to numeric

Conditions = {}
code = 1
for condition in df.Condition.unique():
    Conditions[condition] = code
    code+=1
    
df.replace(Conditions, inplace=True) 

In [558]:
df.Condition.unique()

array([1, 2, 3], dtype=int64)

In [559]:
#Since both coloumns have some common colors,

exterior_colors = {}
ext_code = 1
for color in df['Exterior_Color'].unique():
    exterior_colors[color] = ext_code
    ext_code += 1

interior_colors = {}
int_code = 1
for color in df['Interior_Color'].unique():
    interior_colors[color] = int_code
    int_code += 1

df['Exterior_Color'] = df['Exterior_Color'].replace(exterior_colors)
df['Interior_Color'] = df['Interior_Color'].replace(interior_colors)

In [560]:
df.Exterior_Color.unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167], dtype=int64)

In [561]:
df.Interior_Color.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62], dtype=int64)

In [562]:
df.Fuel_Type.unique()

array(['Gasoline', 'Hybrid', 'Compressed Natural Gas'], dtype=object)

In [563]:
#Recoding the enteries in this column to numeric

Fuel_Types = {}
code = 1
for Fuel_Type in df.Fuel_Type.unique():
    Fuel_Types[Fuel_Type] = code
    code+=1
    
df.replace(Fuel_Types, inplace=True)

In [564]:
df.Fuel_Type.unique()

array([1, 2, 3], dtype=int64)

In [565]:
df.Transmission.unique()

array(['Automatic', 'Automatic CVT', '9-Speed Automatic',
       '10-Speed Automatic', '10-SPEED A/T', 'continuously variable',
       'continuously variable (m cvt)', 'continuously variable automatic',
       'electronic continuously variable', '1-Speed CVT with Overdrive',
       '9-SPEED A/T', 'Variable', 'OTHER', '6-Speed Manual',
       '9-Speed Automatic with Overdrive', 'eCVT', 'Manual',
       'continuously variable w/sport mode',
       'continuously variable (ll cvt)', '10 speed automatic',
       '1-Speed Automatic', 'CVT', 'Electronically Controlled Automatic',
       '6-SPEED M/T', '5-Speed Automatic', '6-Speed Automatic',
       '10-Speed Automatic with Overdrive', '4-Speed Automatic',
       '9 speed automatic', '5-Speed Manual', '6-SPEED A/T',
       '5-SPEED A/T', 'TRANSMISSION W DRIVER SELECTABLE MODE',
       'Close-Ratio 6-Speed Manual', '5-SPEED M/T', '4-SPEED A/T',
       'continuously variable (cvt)', 'AUTOMATIC',
       'e continuously variable (e cvt)',
       

In [566]:
#Recoding the enteries in this column to numeric

Transmissions = {}
code = 1
for transmission in df.Transmission.unique():
    Transmissions[transmission] = code
    code+=1
    
df.replace(Transmissions, inplace=True)

In [567]:
df.Transmission.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
      dtype=int64)

In [568]:
df.Engine.unique()

array(['3.5L V6 24V GDI SOHC', '2.0L I4 16V GDI DOHC Hybrid',
       '3.5L V6 24V GDI DOHC', '1.5L I4 16V GDI DOHC Turbo',
       'V6 Cylinder Engine', '4 Cylinder Engine', '1.5L I4 16V DOHC',
       '2.0L I4 16V GDI DOHC Turbo', '2.0L I4 16V MPFI DOHC Hybrid',
       'Intercooled Turbo Regular Unleaded I-4 1.5 L/91',
       '2.0L I4 16V GDI DOHC', '1.8L I4 16V MPFI SOHC',
       'Gas/Electric I-4 2.0 L/122',
       'Intercooled Turbo Regular Unleaded I-4 2.0 L/122',
       'Regular Unleaded V-6 3.5 L/212', '1.5L 4 Cylinder',
       '2.4L I4 16V GDI DOHC', 'Regular Unleaded I-4 2.0 L/122',
       'Premium Unleaded V-6 3.5 L/212', '2.4L I4 16V MPFI DOHC',
       '1.5L I4 16V MPFI DOHC Hybrid', '2.0L I4 16V MPFI DOHC',
       '2.2L I4 16V MPFI DOHC', '3.5L V6 24V MPFI SOHC', '1.5L 4 Cyl.',
       'Gas/Electric I-4 1.5 L/91', '3.0L V6 24V MPFI SOHC',
       '2.2L I4 16V MPFI SOHC', '1.5L I4', '3.5L', '3.5L V6 DOHC 24V',
       '1.5L I4 16V MPFI SOHC Hybrid', 'Gas/Electric I4 1.5L/91',
   

In [569]:
#Recoding the enteries in this column to numeric

Engines = {}
code = 1
for Engine in df.Engine.unique():
    Engines[Engine] = code
    code+=1
    
df.replace(Engines, inplace=True)

In [570]:
df.Engine.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68],
      dtype=int64)

In [571]:
df.head()

Year  Make  Model  Condition    Price  Consumer_Rating  Consumer_Review_#  \
0     1     1      1          1  46370.0              4.8                  9   
1     1     1      2          1  34150.0              1.7                 24   
2     1     1      2          1  34245.0              4.7               2869   
3     2     1      3          1  46500.0              5.0                 12   
4     1     1      4          1  40395.0              4.4                 12   

   Exterior_Color  Interior_Color         Drivetrain  ...   Stock_#  Mileage  \
0               1               1    All-wheel Drive  ...    830164       10   
1               1               2                FWD  ...   6402953        –   
2               2               2  Front-wheel Drive  ...  PH704805        1   
3               3               2    All-wheel Drive  ...  5700429B        5   
4               4               2    All-wheel Drive  ...   5705954        5   

   Comfort_Rating  Interior_Design_Rating Performance_Rating  \
0             5.0                     4.8                4.8   
1             5.0                     3.0                4.0   
2             5.0                     3.0                4.0   
3             5.0                     5.0                5.0   
4             5.0                     3.0                4.0   

  Value_For_Money_Rating Exterior_Styling_Rating  Reliability_Rating  State  \
0                    4.2                     5.0                 5.0     CA   
1                    4.0                     5.0                 5.0     CA   
2                    4.0                     5.0                 5.0     CA   
3                    5.0                     5.0                 5.0     CA   
4                    4.0                     5.0                 5.0     CA   

   Seller_Type  
0       Dealer  
1       Dealer  
2       Dealer  
3       Dealer  
4       Dealer  

[5 rows x 25 columns]

<font size="5"> Selecting the x and y variables</font>

In [572]:
#Selecting the x and y variables

columns = ['Year', 'Make', 'Model', 'Condition',"Exterior_Color", "Interior_Color", "Fuel_Type", "Transmission", "Engine",'Comfort_Rating',
       'Performance_Rating']

x = df[ columns ]

y = df.Price

<font size="5"> Splitting the data</font>

In [573]:
#splitting the data
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.2)

<font size="5"> LinearRegression model</font>

np.random.seed(42)


In [574]:
#model_1 = LinearRegression

model_1 = LinearRegression()

In [575]:

# fitting the model to the training data

model_1.fit (x_train,y_train)

LinearRegression()

In [576]:
# predictions on the testing data

predicted = model_1.predict( x_test)

In [577]:
y.head()

0    46370.0
1    34150.0
2    34245.0
3    46500.0
4    40395.0
Name: Price, dtype: float64

In [578]:
error = mean_squared_error(y_test,predicted )

In [579]:
print (error)

41369958.47608927


In [580]:
np.sqrt(error)

6431.9482644133

In [581]:
#Accuracy of the Linear Regression using the R-square score
from sklearn.metrics import r2_score

# Calculate the R-squared score
r2 = r2_score(y_test,predicted)

In [582]:
# Print the R-squared score
print('R-squared:', r2)

R-squared: 0.6008422510643469



<font size="5"> LogisticRegression model </font>

In [583]:
# Create a logistic regression model
#model_2 = LogisticRegression

model_2 = LogisticRegression(solver='sag', max_iter=100000)


In [584]:
# Training the model

model_2.fit(x_train, y_train)

LogisticRegression(max_iter=100000, solver='sag')

In [599]:
# predictions on the testing data

predicted_1 = model_2.predict( x_test)

In [600]:
error_1 = mean_squared_error(y_test,predicted )

In [601]:
print(error_1)

41369958.47608927


In [602]:
np.sqrt(error_1)

6431.9482644133

In [603]:
r3 = r2_score(y_test,predicted_1)

In [604]:
# Print the R-squared score
print('R-squared:', r3)

R-squared: 0.5766577844526384
